#!/bin/bash

set -euo pipefail

# args are something like "origin" "git@github.com:CloudCompilers/klotho.git"
# pwd is repo root

if [[ "${SKIP_KLOTHO_CI_CHECKS-0}" == '1' ]]; then
  # I'm not highlighting these
  echo ''
  echo '╭───────────────────────────────────────────────────────────────────────────────────────────╮'
  echo '│ Skipping CI checks. To run them, export SKIP_KLOTHO_CI_CHECKS=0 (or unset it altogether). │'
  echo '╰───────────────────────────────────────────────────────────────────────────────────────────╯'
  exit 0
fi

echo '╭──────────────────────────────────────────────────────────────────╮'
echo '│ Running CI checks. To skip them, export SKIP_KLOTHO_CI_CHECKS=1. │'
echo '╰──────────────────────────────────────────────────────────────────╯'

echo 'Running tests...'
go test -race ./...
echo 

if hash golangci-lint ; then
  printf 'Running golangci-lint... '
  # The sed line replaces the first char with "\n<char>"
  # This just adds a newline to the printf above, but only if there's any output.
  # (golangci-lint only outputs anything if there's a problem)
  if (golangci-lint --color always run | sed -E 's/(.)/\n\1/') ; then
    printf 'success\n'
  fi
else
  echo "⚠️  Couldn't find golangci-lint"
  echo "   To install it follow: https://golangci-lint.run/usage/install/#local-installation"
  exit 1
fi

if hash prettier ; then
  printf 'Running prettier... '
  prettier -c pkg/**/*.ts
else
  echo "⚠️  Couldn't find prettier"
  echo "   To install it: npm install -g prettier"
  exit 1
fi
echo '────────────────────────────────────────────────────────────────────'
