source: aws:api_deployment
destination: aws:api_integration
deployment_order_reversed: false
deletion_dependent: false
reuse:
configuration:
  - resource: aws:api_deployment
    config:
      field: Triggers[aws:api_integration:#Name]
      value: aws:api_integration:#Name
