[linters-settings.lll]
line-length = 120
tab-width = 2

[linters]
# enable after fixing long lines
# there's currently no way to only log violations in golangci-lint
# https://github.com/golangci/golangci-lint/issues/1981
# enable = ["lll"]

[run]
# Don't bother linting test files
skip-files = ["pkg/.*_test.go"]

[[issues.exclude-rules]]
# Temporarily disable linting rangefunc until it's supported
# https://github.com/dominikh/go-tools/issues/1494
linters = ["typecheck"]
text = "cannot range over"
