# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x06klotho\"0\n\tIRRequest\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x14\n\x0cyaml_payload\x18\x02 \x01(\t\"\x1a\n\x07IRReply\x12\x0f\n\x07message\x18\x01 \x01(\t2?\n\rKlothoService\x12.\n\x06SendIR\x12\x11.klotho.IRRequest\x1a\x0f.klotho.IRReply\"\x00\x42:Z8github.com/klothoplatform/klotho/pkg/k2/language_host/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/klothoplatform/klotho/pkg/k2/language_host/go'
  _globals['_IRREQUEST']._serialized_start=25
  _globals['_IRREQUEST']._serialized_end=73
  _globals['_IRREPLY']._serialized_start=75
  _globals['_IRREPLY']._serialized_end=101
  _globals['_KLOTHOSERVICE']._serialized_start=103
  _globals['_KLOTHOSERVICE']._serialized_end=166
# @@protoc_insertion_point(module_scope)
