# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07\x65xample\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\rPythonRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1f\n\x0bPythonReply\x12\x10\n\x08response\x18\x01 \x01(\t2\x8f\x01\n\x0e\x45xampleService\x12\x38\n\x08SayHello\x12\x15.example.HelloRequest\x1a\x13.example.HelloReply\"\x00\x12\x43\n\x11GetPythonResponse\x12\x16.example.PythonRequest\x1a\x14.example.PythonReply\"\x00\x42:Z8github.com/klothoplatform/klotho/pkg/k2/language_host/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/klothoplatform/klotho/pkg/k2/language_host/go'
  _globals['_HELLOREQUEST']._serialized_start=26
  _globals['_HELLOREQUEST']._serialized_end=54
  _globals['_HELLOREPLY']._serialized_start=56
  _globals['_HELLOREPLY']._serialized_end=85
  _globals['_PYTHONREQUEST']._serialized_start=87
  _globals['_PYTHONREQUEST']._serialized_end=117
  _globals['_PYTHONREPLY']._serialized_start=119
  _globals['_PYTHONREPLY']._serialized_end=150
  _globals['_EXAMPLESERVICE']._serialized_start=153
  _globals['_EXAMPLESERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
