qualified_type_name: kubernetes:config_map
display_name: ConfigMap
sanitize_name:
  # a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',
  # and must start and end with an alphanumeric character
  # (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
  |
  {{ . 
    | replace `[^a-zA-Z0-9-]+` "" | replace `^[-]+` "" | replace `[-]+$` "" | length 1 50 
  }}

properties:
  Cluster:
    type: resource
    namespace: true
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - classifications:
                - cluster
                - kubernetes
  Object:
    type: map
    properties:
      kubernetes:TypeMeta:
        type: model
        default_value:
          apiVersion: v1
          kind: ConfigMap
      metadata:
        type: model(kubernetes:ObjectMeta)
      immutable:
        type: bool
      data:
        type: map(string,string)

delete_context:
  requires_no_downstream: true
views:
  dataflow: small
