qualified_type_name: kubernetes:deployment
display_name: K8s Deployment
sanitize_name:
  # a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',
  # and must start and end with an alphanumeric character
  # (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
  |
  {{ . 
    | replace `[^a-zA-Z0-9-]+` "" | replace `^[-]+` "" | replace `[-]+$` "" | length 1 50 
  }}

properties:
  Cluster:
    type: resource
    namespace: true
    operational_rule:
      step:
        direction: downstream
        resources:
          - classifications:
              - cluster
              - kubernetes
  Object:
    type: map
    properties:
      kubernetes:TypeMeta:
        type: model
        default_value:
          apiVersion: apps/v1
          kind: Deployment
      metadata:
        type: model(kubernetes:ObjectMeta)
      spec:
        type: map
        properties:
          replicas:
            type: int
            default_value: 2
          selector:
            type: model(kubernetes:LabelSelector)
          template:
            type: model(kubernetes:PodTemplateSpec)
          strategy:
            type: map
            properties:
              type:
                type: string
                default_value: RollingUpdate
              rollingUpdate:
                type: map
                properties:
                  maxUnavailable:
                    type: any
                    default_value: 1
                  maxSurge:
                    type: any
                    default_value: 1

path_satisfaction:
  as_target:
    - service
    - network#Cluster
  as_source:
    - network#Cluster#Subnets

classification:
  is:
    - compute
    - container
    - replicas

delete_context:
  requires_no_upstream: true
views:
  dataflow: big
