qualified_type_name: kubernetes:kube_config
display_name: KubeConfig

properties:
  name:
    type: string
  apiVersion:
    type: string
  kind:
    type: string
  currentContext:
    type: string
  clusters:
    type: list
    properties:
      name:
        type: string
      cluster:
        type: map(string,string)
  contexts:
    type: list
    properties:
      name:
        type: string
      context:
        type: map
        properties:
          cluster:
            type: string
          user:
            type: string
  users:
    type: list
    properties:
      name:
        type: string
      user:
        type: map
        properties:
          exec:
            type: map
            properties:
              apiVersion:
                type: string
              command:
                type: string
              args:
                type: list(string)
