qualified_type_name: kubernetes:kustomize_directory
display_name: Kustomize Directory

properties:
  Cluster:
    type: resource
    namespace: true
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - classifications:
                - cluster
                - kubernetes
  Directory:
    type: string

delete_context:
  requires_no_upstream: true
views:
  dataflow: small
