qualified_type_name: kubernetes:manifest
display_name: Kubernetes Manifest
sanitize_name:
  # a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',
  # and must start and end with an alphanumeric character
  # (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
  |
  {{ . 
    | replace `[^a-zA-Z0-9-]+` "" | replace `^[-]+` "" | replace `[-]+$` ""
  }}

properties:
  FilePath:
    type: string
    Transformations:
      type: map(string,string)
  Cluster:
    type: resource
    namespace: true
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - classifications:
                - cluster
                - kubernetes

delete_context:
  require_no_upstream: true
views:
  dataflow: small
