qualified_type_name: kubernetes:namespace
display_name: Namespace
properties:
  Cluster:
    type: resource
    namespace: true
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - classifications:
              - cluster
              - kubernetes
  Object:
    type: map
    properties:
      kubernetes:TypeMeta:
        type: model
      kubernetes:ObjectMeta:
        type: model

delete_context:
  requires_no_downstream: true
views:
  dataflow: small
