qualified_type_name: kubernetes:persistent_volume
display_name: Persistent Volume

sanitize_name:
  # a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',
  # and must start and end with an alphanumeric character
  # (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
  |
  {{ . 
    | replace `[^a-zA-Z0-9-]+` "" | replace `^[-]+` "" | replace `[-]+$` ""
  }}


properties:
  Cluster:
    type: resource
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - classifications:
                - cluster
                - kubernetes
  Object:
    type: map
    properties:
      kubernetes:TypeMeta:
        type: model
        default_value:
          ApiVersion: v1
          Kind: PersistentVolume
      Metadata:
        type: model(kubernetes:ObjectMeta)
      Spec:
        type: map
        properties:
          Capacity:
            type: map(string,string)
          kubernetes:PersistentVolumeSource:
            type: model
          AccessModes:
            type: list(string)
          MountOptions:
            type: list(string)
          StorageClassName:
            type: resource(kubernetes:storage_class)
            operational_rule:
              steps:
                - direction: upstream
                  resources:
                    - kubernetes:storage_class
          VolumeMode:
            type: string

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small
