qualified_type_name: kubernetes:pod
display_name: Kubernetes Pod

properties:
  Cluster:
    type: resource
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - classifications:
                - cluster
                - kubernetes
  Object:
    type: map
    properties:
      kubernetes:TypeMeta:
        type: model
        default_value:
          ApiVersion: v1
          Kind: Pod
      Metadata:
        type: model(kubernetes:ObjectMeta)
      Spec:
        type: model(kubernetes:PodSpec)

classification:
  is:
    - compute
    - container

delete_context:
  requires_no_upstream: true
views:
  dataflow: big
