qualified_type_name: kubernetes:service
display_name: Service

sanitize_name:
  # a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',
  # and must start and end with an alphanumeric character
  # (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
  |
  {{ . 
    | replace `[^a-zA-Z0-9-]+` "" | replace `^[-]+` "" | replace `[-]+$` ""
  }}


properties:
  Cluster:
    type: resource
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - classifications:
                - cluster
                - kubernetes
  Object:
    type: map
    properties:
      kubernetes:TypeMeta:
        type: model
        default_value:
          ApiVersion: v1
          Kind: Service
      Metadata:
        type: model(kubernetes:ObjectMeta)
      Spec:
        type: map
        properties:
          Ports:
            type: list
            properties:
              Name:
                type: string
              Protocol:
                type: string
                default_value: TCP
              Port:
                type: int
              TargetPort:
                type: int
              NodePort:
                type: int
          Selector:
            type: map(string,string)
          ServiceType:
            type: string
            default_value: ClusterIP
          SessionAffinity:
            type: string

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small
