qualified_type_name: kubernetes:service
display_name: Service

sanitize_name:
  # a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',
  # and must start and end with an alphanumeric character
  # (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
  |
  {{ . 
    | replace `[^a-zA-Z0-9-]+` "" | replace `^[-]+` "" | replace `[-]+$` ""
  }}


properties:
  Cluster:
    type: resource
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - classifications:
                - cluster
                - kubernetes
  Object:
    type: map
    properties:
      kubernetes:TypeMeta:
        type: model
        default_value:
          apiVersion: v1
          kind: Service
      metadata:
        type: model(kubernetes:ObjectMeta)
      spec:
        type: map
        properties:
          ports:
            type: list
            properties:
              name:
                type: string
              protocol:
                type: string
                default_value: TCP
              port:
                type: int
                default_value: 80
              targetPort:
                type: int
                default_value: 80
              nodePort:
                type: int
          selector:
            type: map(string,string)
          serviceType:
            type: string
            default_value: ClusterIP
          sessionAffinity:
            type: string

path_satisfaction:
  as_target:
    - network#Cluster#Subnets

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small
