qualified_type_name: kubernetes:storage_class
display_name: Storage Class

sanitize_name:
  # a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',
  # and must start and end with an alphanumeric character
  # (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
  |
  {{ . 
    | replace `[^a-zA-Z0-9-]+` "" | replace `^[-]+` "" | replace `[-]+$` ""
  }}


properties:
  Cluster:
    type: resource
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - classifications:
                - cluster
                - kubernetes
  Object:
    type: map
    properties:
      kubernetes:TypeMeta:
        type: model
        default_value:
          ApiVersion: storage.k8s.io/v1
          Kind: StorageClass
      Metadata:
        type: model(kubernetes:ObjectMeta)
      Provisioner:
        type: string
      Parameters:
        type: map(string,string)
      MountOptions:
        type: list(string)
      AllowVolumeExpansion:
        type: boolean
      ReclaimPolicy:
        type: string
      VolumeBindingMode:
        type: string

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small
