provider: kubernetes
type: deployment
rules:
  - enforcement: exactly_one
    direction: downstream
    classifications:
      - cluster
      - kubernetes
    set_field: Cluster
    unsatisfied_action:
      operation: create
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - service_account
    unsatisfied_action:
      operation: create
      unique: true
delete_context:
  requires_no_upstream: true
  requires_explicit_delete: true
configuration:
  - field: Object.Kind
    value: Deployment
  - field: Object.APIVersion
    value: apps/v1
  - field: Object.Spec.Replicas
    value: 2
  - field: Object.Spec.Strategy
    value:
      RollingUpdate:
        MaxSurge: 1
        MaxUnavailable: 1
      Type: RollingUpdate
views:
  dataflow: big