provider: kubernetes
type: deployment
rules:
  - enforcement: exactly_one
    direction: downstream
    classifications:
      - cluster
      - kubernetes
    set_field: Cluster
    unsatisfied_action:
      operation: create
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - service_account
    unsatisfied_action:
      operation: create
      unique: true
delete_context:
  requires_no_upstream: true
  requires_explicit_delete: true
configuration:
  - field: Object
    value:
      TypeMeta:
        APIVersion: apps/v1
        Kind: Deployment
      Spec:
        Replicas: 2
        Strategy:
          RollingUpdate:
            MaxSurge: 1
            MaxUnavailable: 1
          Type: RollingUpdate
