provider: kubernetes
type: helm_chart
rules:
  - enforcement: exactly_one
    direction: downstream
    classifications:
      - cluster
      - kubernetes
    set_field: Cluster
    unsatisfied_action:
      operation: create
delete_context:
  requires_no_upstream: true
views:
  dataflow: big