provider: kubernetes
type: kubeconfig
rules:
  - enforcement: exactly_one
    direction: downstream
    classifications:
      - cluster
      - kubernetes
    unsatisfied_action:
      operation: error
delete_context:
  requires_no_upstream: true
