provider: kubernetes
type: pod
rules:
  - enforcement: exactly_one
    direction: downstream
    classifications:
      - cluster
      - kubernetes
    set_field: Cluster
    unsatisfied_action:
      operation: create
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - service_account
    unsatisfied_action:
      operation: create
      unique: true
delete_context:
  requires_no_upstream: true
  requires_explicit_delete: true
configuration:
  - field: Object
    value:
      APIVersion: v1
      Kind: Pod
      Metadata:
        Labels:
          execUnit: "{{ .ExecUnitName }}"
        Name: "{{ .Name }}"
        Namespace: "{{ .Namespace }}"
        Spec:
          Containers:
            - Image: REPLACE_ME
              Name: "{{ .Name }}"
          ServiceAccountName: "{{ .ServiceAccountName }}"

