provider: kubernetes
type: pod
rules:
  - enforcement: exactly_one
    direction: downstream
    classifications:
      - cluster
      - kubernetes
    set_field: Cluster
    unsatisfied_action:
      operation: create
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - service_account
    unsatisfied_action:
      operation: create
      unique: true
delete_context:
  requires_no_upstream: true
  requires_explicit_delete: true
configuration:
  - field: Object.Kind
    value: Pod
  - field: Object.APIVersion
    value: v1
views:
  dataflow: big
