provider: kubernetes
type: service_account
rules:
  - enforcement: exactly_one
    direction: downstream
    classifications:
      - cluster
      - kubernetes
    set_field: Cluster
    unsatisfied_action:
      operation: create
delete_context:
  requires_no_upstream: true
configuration:
  - field: Object
    value:
     TypeMeta:
       APIVersion: v1
       Kind: ServiceAccount
     ObjectMeta:
       Name: "{{ .Name }}"
     AutomountServiceAccountToken: true
