provider: kubernetes
type: service
rules:
  - enforcement: exactly_one
    direction: downstream
    classifications:
      - cluster
      - kubernetes
    set_field: Cluster
    unsatisfied_action:
      operation: create
delete_context:
  requires_no_upstream: true
configuration:
  - field: Object.APIVersion
    value: v1
  - field: Object.Kind
    value: Service
views:
  dataflow: small