qualified_type_name: aws:ami
display_name: AMI

properties:
  aws:tags:
    type: model

classification:
  is:
    - machine_image
delete_context:
  requires_no_upstream: true
views:
  dataflow: small

deployment_permissions:
  deploy: ["ec2:CreateImage"]
  tear_down: ["ec2:DeregisterImage"]
  update: ["ec2:ModifyImageAttribute"]