qualified_type_name: aws:api_deployment
display_name: API Deployment

properties:
  RestApi:
    type: resource(aws:rest_api)
    namespace: true
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:rest_api
  Triggers:
    type: map(string,string)

classification:

delete_context:
  requires_no_upstream: true
views:
  dataflow: small

deployment_permissions:
  deploy: ["apigateway:CreateDeployment"]
  tear_down: ["apigateway:DeleteDeployment"]
  update: ["apigateway:UpdateDeployment"]