qualified_type_name: aws:api_method
display_name: API Method

properties:
  RestApi:
    type: resource(aws:rest_api)
    namespace: true
    operational_rule:
      steps:
        - direction: upstream
          resources:
            - aws:rest_api
  Resource:
    type: resource(aws:api_resource)
    operational_rule:
      steps:
        - direction: upstream
          resources:
            - aws:api_resource
  HttpMethod:
    type: string
    default_value: ANY
  RequestParameters:
    type: map(string,string)
  Authorization:
    type: string
    default_value: NONE

classification:
  is:
    - api_route

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small
