qualified_type_name: aws:api_resource
display_name: API Resource

properties:
  RestApi:
    type: resource(aws:rest_api)
    namespace: true
    operational_rule:
      step:
        direction: upstream
        resources:
          - aws:rest_api
    description: A reference to the specific AWS REST API object that this API resource
      is associated with
  ParentResource:
    type: resource(aws:api_resource)
    configuration_disabled: true
    operational_rule:
      if: | # Only need a parent resource if this one isn't the root
        {{ $parts := slice (split (fieldValue "FullPath" .Self) "/") 1 }}
        {{ gt (len $parts) 1 }}
      step:
        direction: upstream
        resources:
          - selector: |
              {{ $parts := split (fieldValue "FullPath" .Self) "/" -}}
              {{ $parts := slice $parts 1 (sub (len $parts) 1) -}}
              aws:api_resource:{{ join $parts "-" | sanitizeName }}
            properties:
              FullPath: |
                {{ $parts := split (fieldValue "FullPath" .Self) "/" -}}
                {{ $parts := slice $parts 0 (sub (len $parts) 1) -}}
                {{ join $parts "/" }}
              RestApi: '{{ fieldValue "RestApi" .Self }}'
    description: The identifier of the parent API resource if this resource is not
      at the root
  FullPath:
    type: string
    configuration_disabled: true
    description: The complete path for the API resource, used to define the resource
      in AWS API Gateway
  PathPart:
    type: string
    configuration_disabled: true
    default_value: |
      {{ $parts := split (fieldValue "FullPath" .Self) "/" -}}
      {{ last $parts }}

    description: A segment of the FullPath representing this resource's position in
      the hierarchy
classification:

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small
