qualified_type_name: aws:api_stage
display_name: API Stage

properties:
  StageName:
    type: string
    default_value: stage
  RestApi:
    type: resource(aws:rest_api)
    namespace: true
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:rest_api
  Deployment:
    type: resource(aws:api_deployment)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:api_deployment
  aws:tags:
    type: model
  StageInvokeUrl:
    type: string
    configuration_disabled: true
    deploy_time: true

classification:
  is:
    - cloudfront_origin
    - api_stage

delete_context:
  requires_no_upstream: true

views:
  dataflow: small

deployment_permissions:
  deploy: ["apigateway:CreateStage"]
  tear_down: ["apigateway:DeleteStage"]
  update: ["apigateway:UpdateStage"]