qualified_type_name: aws:api_integration
display_name: API Integration

properties:
  RestApi:
    type: resource(aws:rest_api)
    namespace: true
    operational_rule:
      steps:
        - direction: upstream
          resources:
            - aws:rest_api
  Resource:
    type: resource(aws:api_resource)
    operational_rule:
      if: | # Need to replace the resource if the path parts is not the same as the route
        {{ $route := (fieldValue "Route" .Self) }} 
        {{ $path := longestPath (fieldValue "RestApi" .Self) .Self }}
        {{ $resourceRoute := "" }}
        {{ range $index, $element := $path }}
          {{ if eq $element.QualifiedTypeName "aws:api_resource" }}
            {{ $resourcePath := (fieldValue "PathPart" $element) }}
            {{ $resourceRoute = (print $resourceRoute "/" $resourcePath) }}
          {{ end }}
        {{ end }}
        {{ ne $resourceRoute $route }}
      steps:
        - direction: upstream
          replacement_condition: true
          resources:
            - |
              {{ $route := (fieldValue "Route" .Self) }} 
              {{ $path := longestPath (fieldValue "RestApi" .Self) .Self }}
              {{ $resourceRoute := "" }}
              {{ range $index, $element := $path }}
                {{ if eq $element.QualifiedTypeName "aws:api_resource" }}
                  {{ $resourcePath := (fieldValue "PathPart" $element) }}
                  {{ $resourceRoute = (print $resourceRoute "/" $resourcePath) }}
                {{ end }}
              {{ end }}
              {{- if eq $resourceRoute $route }}
                {{ upstream "aws:api_resource" .Self }}
              {{- else }}
                aws:api_resource:{{ fieldValue "Route" .Self | replace "\\{([^}+]+)\\+?\\}" "$1" | replace "^/" "" | replace "/" "-" }}
              {{- end }}
  Method:
    type: resource(aws:api_method)
    operational_rule:
      steps:
        - direction: upstream
          resources:
            - '{{ longestPath (fieldValue "RestApi" .Self) .Self | firstId "aws:api_method" }}'
  RequestParameters:
    type: map(string,string)
    operational_rule:
      configuration_rules:
        - resource: '{{ .Self }}'
          configuration:
            field: RequestParameters
            value: |
              {{ $params := split (fieldValue "Route" .Self) "/" | filterMatch "^:\\w+$" }}
              {{ zipToMap
                  ($params | mapString ":(.*)" "integration.request.path.$1")
                  ($params | mapString ":(.*)" "method.request.path.$1")
                | toJson
              }}
  IntegrationHttpMethod:
    type: string
    default_value: ANY
  Type:
    type: string
  ConnectionType:
    type: string
  VpcLink:
    type: resource(aws:vpc_link)
  Uri:
    type: string
  Route:
    type: string
    default_value: /{proxy+}

classification:

delete_context:
  requires_no_upstream_or_downstream: true

views:
  dataflow: small
