qualified_type_name: aws:api_method
display_name: API Method

deletion_dependent: true # Because both integration and method depend on resource we need to not use these edges to reflect deletion

properties:
  RestApi:
    type: resource(aws:rest_api)
    namespace: true
    operational_rule:
      step:
        direction: upstream
        resources:
          - aws:rest_api
    description: The identifier of the AWS REST API resource to which this method
      belongs
  Resource:
    type: resource(aws:api_resource)
    operational_rule:
      if: |
        {{ ne (fieldValue "Route" (downstream "aws:api_integration" .Self)) "/" }}
      step:
        direction: upstream
        resources:
          - selector: aws:api_resource
            properties:
              FullPath: '{{ fieldValue "Route" (downstream "aws:api_integration" .Self) }}'
  HttpMethod:
    type: string
    default_value: ANY
    allowed_values:  # Added allowed_values field
      - ANY
      - GET
      - POST
      - PUT
      - DELETE
      - HEAD
      - PATCH
      - OPTIONS
    description: The HTTP method type (e.g., GET, POST, PUT, DELETE, HEAD, PATCH, OPTIONS) for the API resource's
      method request
  RequestParameters:
    type: map(string,bool)
    description: A map of request parameter names to specifications on whether they
      are required for the method
  Authorization:
    type: string
    default_value: NONE
    allowed_values:  # Added allowed_values field
      - NONE
      - AWS_IAM
      - CUSTOM
    description: The type of authorization used for the API method, such as NONE,
      AWS_IAM, or CUSTOM
classification:
  is:
    - api_route

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small
