qualified_type_name: aws:api_integration
display_name: API Integration

properties:
  RestApi:
    type: resource(aws:rest_api)
    namespace: true
    operational_rule:
      steps:
        - direction: upstream
          resources:
            - aws:rest_api
  Resource:
    type: resource(aws:api_resource)
    operational_rule:
      steps:
        - direction: upstream
          resources:
            - selector: 'aws:api_resource'
              properties:
                FullPath: '{{ fieldValue "Route" .Self }}'
                RestApi: '{{ fieldValue "RestApi" .Self }}'
  Method:
    type: resource(aws:api_method)
    operational_rule:
      steps:
        - direction: upstream
          resources:
            - selector: aws:api_method
  RequestParameters:
    type: map(string,string)
    operational_rule:
      configuration_rules:
        - resource: '{{ .Self }}'
          configuration:
            field: RequestParameters
            value: |
              {{ $params := split (fieldValue "Route" .Self) "/" | filterMatch "^:\\w+$" }}
              {{ zipToMap
                  ($params | mapString ":(.*)" "integration.request.path.$1")
                  ($params | mapString ":(.*)" "method.request.path.$1")
                | toJson
              }}
  IntegrationHttpMethod:
    type: string
    default_value: ANY
  Type:
    type: string
  ConnectionType:
    type: string
  VpcLink:
    type: resource(aws:vpc_link)
  Uri:
    type: string
  Route:
    type: string
    default_value: /{proxy+}

classification:
  is:
    - api_route
    - api_integration

delete_context:
  requires_no_upstream_or_downstream: true

views:
  dataflow: big
