qualified_type_name: aws:api_deployment
display_name: API Deployment

properties:
  RestApi:
    type: resource(aws:rest_api)
    namespace: true
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - aws:rest_api
  Triggers:
    type: map(string,string)
    configuration_disabled: true
    default_value: |
      {{ $api := fieldValue "RestApi" .Self }}
      {{ $integrations := allDownstream "aws:api_integration" $api}}
      {{ $methods := allDownstream "aws:api_method" $api }}
      {
        {{- range $index, $integration := $integrations }}
          "integ/{{ $integration.Name }}": "{{ $integration.Name }}"{{ if or (ne $index (sub (len $integrations) 1)) (ne (len $methods) 0) }},{{ end}}
        {{- end }}
        {{- range $index, $method := $methods }}
          "method/{{ $method.Name }}": "{{ $method.Name }}"{{ if ne $index (sub (len $integrations) 1) }},{{ end}}
        {{- end }}
      }

classification:

delete_context:
  requires_no_upstream: true
views:
  dataflow: small
