qualified_type_name: aws:app_runner_service
display_name: App Runner
sanitize_name:
  # https://docs.aws.amazon.com/apprunner/latest/api/API_Service.html (ServiceName)
  # Pattern: [A-Za-z0-9][A-Za-z0-9-_]{3,39}
  |
  {{ .
    | replace `^[^A-Za-z0-9]+` ""
    | replace `[^A-Za-z0-9-_]+` ""
    | length 4 40
  }}

properties:
  Image:
    type: resource(aws:ecr_image)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:ecr_image:{{ .Self.Name }}-image
        unique: true
    description: The image repository that contains the application image to be run
      by App Runner
  InstanceRole:
    type: resource(aws:iam_role)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:iam_role:{{ .Self.Name }}-instance-role
        unique: true
    description: The IAM role that provides the AWS permissions that the App Runner
      service assumes when it accesses your resources
  EnvironmentVariables:
    type: map(string,string)
    description: Key-value pairs of environment variables that are provided to the
      App Runner service
    key_property:
      sanitize: |
        {{ .
          | replace `[^[:alnum:]_]+` "_"
          | replace `^[^a-zA-Z]+` ""
          | upper
        }}
  Port:
    type: int
    default_value: 8080

    description: The network port that the App Runner service listens to for incoming
      traffic
classification:
  is:
    - compute
    - container
    - serverless

views:
  dataflow: big
