qualified_type_name: aws:cloudfront_distribution
display_name: CloudFront Distribution

properties:
  Origins:
    type: list
    properties:
      DomainName:
        type: string
      OriginId:
        type: string
      OriginPath:
        type: string
      S3OriginConfig:
        type: map
        properties:
          OriginAccessIdentity:
            type: string
      CustomOriginConfig:
        type: map
        properties:
          HttpPort:
            type: int
          HttpsPort:
            type: int
          OriginProtocolPolicy:
            type: string
          OriginSslProtocols:
            type: list(string)
  CacheBehaviors:
    type: set
    properties:
      AllowedMethods:
        type: set(string)
        item_property:
          type: string
          allowed_values:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
        default_value:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
      CachedMethods:
        type: set(string)
        item_property:
          type: string
          allowed_values:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
        default_value:
          - HEAD
          - GET
      TargetOriginId:
        type: string
      ForwardedValues:
        type: map
        properties:
          QueryString:
            type: bool
          Cookies:
            type: map
            properties:
              Forward:
                type: string
      MinTtl:
        type: int
        default_value: 0
      MaxTtl:
        type: int
        default_value: 86400
      DefaultTtl:
        type: int
        default_value: 3600
      ViewerProtocolPolicy:
        type: string
        default_value: allow-all
      PathPattern:
        type: string
      SmoothStreaming:
        type: bool
        default_value: false
      CachePolicyId:
        type: string
        default_value: '4135ea2d-6df8-44a3-9df3-4b5a84be39ad' # Managed-CachingDisabled
      OriginRequestPolicyId:
        type: string
        default_value: 'b689b0a8-53d0-40ab-baf2-68738e2966ac' # Managed-AllViewerExceptHostHeader
  ViewerCertificate:
    type: map
    default_value:
      CloudfrontDefaultCertificate: true
    properties:
      AcmCertificateArn:
        type: string
      SslSupportMethod:
        type: string
        allowed_values:
          - sni-only
          - vip
          - static-ip
      MinimumProtocolVersion:
        type: string
        allowed_values:
          - SSLv3
          - TLSv1
          - TLSv1_2016
          - TLSv1.1_2016
          - TLSv1.2_2018
          - TLSv1.2_2019
          - TLSv1.2_2021
      CloudfrontDefaultCertificate:
        type: bool
      IamCertificateId:
        type: string
  Aliases:
    type: list(string)
    description: |
      A list of CNAMEs (aliases) that you want CloudFront to use for this
      distribution. You can have up to 10 CNAMEs in this list.
  CustomErrorResponses:
    type: list
    properties:
      ErrorCachingMinTTL:
        type: int
      ErrorCode:
        type: int
      ResponseCode:
        type: int
      ResponsePagePath:
        type: string
  Enabled:
    type: bool
    default_value: true
  DefaultCacheBehavior:
    type: map
    properties:
      AllowedMethods:
        type: list(string)
        default_value:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
      CachedMethods:
        type: list(string)
        default_value:
          - HEAD
          - GET
      TargetOriginId:
        type: string
      ForwardedValues:
        type: map
        properties:
          QueryString:
            type: bool
          Cookies:
            type: map
            properties:
              Forward:
                type: string
      MinTtl:
        type: int
        default_value: 0
      MaxTtl:
        type: int
        default_value: 86400
      DefaultTtl:
        type: int
        default_value: 3600
      CachePolicyId:
        type: string
        default_value: '4135ea2d-6df8-44a3-9df3-4b5a84be39ad' # Managed-CachingDisabled
      OriginRequestPolicyId:
        type: string
        default_value: 'b689b0a8-53d0-40ab-baf2-68738e2966ac' # Managed-AllViewerExceptHostHeader
      ViewerProtocolPolicy:
        type: string
        default_value: allow-all
  Restrictions:
    type: map
    properties:
      GeoRestriction:
        type: map
        properties:
          RestrictionType:
            type: string
            default_value: none
  DefaultRootObject:
    type: string
  aws:tags:
    type: model
  DomainName:
    type: string
    description: |
      The domain name of the distribution. For example: d111111abcdef8.cloudfront.net.
    deploy_time: true
    configuration_disabled: true
  URLBase:
    type: string
    description: |
      The base URL for the distribution. For example: https://d111111abcdef8.cloudfront.net.
    deploy_time: true
    configuration_disabled: true

path_satisfaction:
  as_source:
    - cloudfront_origin

classification:
  is:
    - cdn
    - network
  gives:
    - low_latency

delete_context:
  requires_no_downstream: true
  requires_no_upstream: true

views:
  dataflow: big

deployment_permissions:
  deploy: ['cloudfront:*Distribution', 'cloudfront:TagResource']
  update: ['cloudfront:UntagResource', 'cloudfront:List*']
