qualified_type_name: aws:dynamodb_table
display_name: DynamoDB Table

properties:
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true
  Attributes:
    type: list
    required: true
    default_value:
      - Name: id
        Type: S
    properties:
      Name:
        type: string
        description: Name of the attribute
      Type:
        type: string
        description: The data type for the attribute, such as String (S) or Number
          (N)
    description: List of attribute definitions for the table which includes attribute
      name and type
  BillingMode:
    type: string
    default_value: PAY_PER_REQUEST
    description: The billing mode that determines how you are charged for read and
      write throughput and how you manage capacity
  DynamoTableStreamArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  DynamoTableBackupArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  DynamoTableExportArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  DynamoTableIndexArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  HashKey:
    type: string
    default_value: id
    required: true
    description: The table hash key, which is the partition key for the DynamoDB table
  RangeKey:
    type: string
    description: The table range key, which is the sort key for the DynamoDB table
  Name:
    type: string
    configuration_disabled: true
    deploy_time: true

path_satisfaction:
  as_target:
    - network
    - permissions

classification:
  is:
    - storage
    - nosql
    - dynamodb
    - serverless
    - kv
    - high-availability
    - scalable

consumption:
  emitted:
    - model: EnvironmentVariables
      value:
        '{{ .Self.Name }}_TABLE_NAME': '{{ fieldRef "Name" .Self }}'


delete_context:
  requires_no_upstream: true
  requires_no_downstream: true

views:
  dataflow: big


deployment_permissions:
  deploy: ["dynamodb:CreateTable"]
  tear_down: ["dynamodb:DeleteTable"]
  update: ["dynamodb:UpdateTable"]