qualified_type_name: aws:dynamodb_table

properties:
  Attributes:
    type: list
    required: true
    default_value:
      - Name: id
        Type: S
    properties:
      Name:
        type: string
      Type: 
        type: string
  BillingMode:
    type: string
    default_value: PAY_PER_REQUEST
  HashKey:
    type: string
    default_value: id
    required: true
  RangeKey:
    type: string
  DynamoTableStreamArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  DynamoTableBackupArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  DynamoTableExportArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  DynamoTableIndexArn:
    type: string
    configuration_disabled: true
    deploy_time: true

classification:
  is:
    - storage
    - nosql
    - dynamodb
    - serverless
    - kv
    - high-availability
    - scalable

delete_context:
  requires_no_upstream: true
  requires_no_downstream: true

views:
  dataflow: big