qualified_type_name: aws:dynamodb_table
display_name: DynamoDB Table

properties:
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true
  Attributes:
    type: list
    required: true
    default_value:
      - Name: id
        Type: S
    properties:
      Name:
        type: string
        description: Name of the attribute
      Type:
        type: string
        description: The data type for the attribute, such as String (S) or Number
          (N)
    description: List of attribute definitions for the table which includes attribute
      name and type
  BillingMode:
    type: string
    default_value: PAY_PER_REQUEST
    description: The billing mode that determines how you are charged for read and
      write throughput and how you manage capacity
  DynamoTableStreamArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  DynamoTableBackupArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  DynamoTableExportArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  DynamoTableIndexArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  HashKey:
    type: string
    default_value: id
    required: true
    description: The table hash key, which is the partition key for the DynamoDB table
  RangeKey:
    type: string
    description: The table range key, which is the sort key for the DynamoDB table
  GlobalSecondaryIndexes:
    type: list
    description: List of global secondary indexes to define on the table
    properties:
      Name:
        type: string
        description: The name of the global secondary index
      HashKey:
        type: string
        description: The partition key for the global secondary index
      RangeKey:
        type: string
        description: The sort key for the global secondary index (optional)
      ProjectionType:
        type: string
        description: The set of attributes that are projected into the index, can be 'ALL', 'KEYS_ONLY', or 'INCLUDE'
      NonKeyAttributes:
        type: list
        description: The non-key attribute names to include in the projection for the index
  LocalSecondaryIndexes:
    type: list
    description: List of local secondary indexes to define on the table
    properties:
      Name:
        type: string
        description: The name of the local secondary index
      RangeKey:
        type: string
        description: The sort key for the local secondary index
      ProjectionType:
        type: string
        description: The set of attributes that are projected into the index, can be 'ALL', 'KEYS_ONLY', or 'INCLUDE'
      NonKeyAttributes:
        type: list
        description: The non-key attribute names to include in the projection for the index
  aws:tags:
    type: model
  Name:
    type: string
    configuration_disabled: true
    deploy_time: true
  Id:
    type: string
    configuration_disabled: true
    deploy_time: true
    required: true

path_satisfaction:
  as_target:
    - network
    - permissions

classification:
  is:
    - storage
    - nosql
    - dynamodb
    - serverless
    - kv
    - high-availability
    - scalable

consumption:
  emitted:
    - model: EnvironmentVariables
      value:
        '{{ .Self.Name }}_TABLE_NAME': '{{ fieldRef "Name" .Self }}'

delete_context:
  requires_no_upstream: true
  requires_no_downstream: true

views:
  dataflow: big

deployment_permissions:
  deploy: ["dynamodb:CreateTable"]
  tear_down: ["dynamodb:DeleteTable"]
  update: ["dynamodb:UpdateTable"]
