qualified_type_name: aws:ec2_instance
display_name: EC2 Instance

properties:
  InstanceProfile:
    type: resource(aws:iam_instance_profile)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:iam_instance_profile:{{ .Self.Name }}
    description: The IAM instance profile to associate with the EC2 instance for role-based
      access to AWS resources
  SecurityGroup:
    type: list(resource(aws:security_group))
    operational_rule:
      step:
        direction: upstream
        resources:
          - aws:security_group
        unique: true
    description: A list of security group resources to be associated with the EC2
      instance for defining network access control
  Subnet:
    type: resource(aws:subnet)
    operational_rule:
      step:
        direction: downstream
        resources:
          - selector: aws:subnet
            properties:
              Type: private
          - aws:subnet
    description: The subnet in which to launch the EC2 instance, allowing for specification
      of a private or default subnet type
  AMI:
    type: resource(aws:ami)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:ami
    description: The Amazon Machine Image resource to use for the EC2 instance, determining
      the OS and initial state
  InstanceType:
    type: string
    default: t3.medium
    description: The type of the EC2 instance, determining the CPU, memory, and other
      resources
  aws:tags:
    type: model
  Id:
    type: string
    configuration_disabled: true
    deploy_time: true

path_satisfaction:
  as_target:
    - network
    - network#Subnet


classification:
  is:
    - compute
    - long_running
    - server
    - linux

delete_context:
  requires_no_upstream: true
  requires_no_downstream: true
views:
  dataflow: big


deployment_permissions:
  deploy: ["ec2:RunInstances"]
  tear_down: ["ec2:TerminateInstances"]
  update: ["ec2:ModifyInstanceAttribute"]