qualified_type_name: aws:ecr_image
properties:
  ImageName:
    type: string
    default_value: '{{ .Self.Name }}'
  BaseImage:
    type: string
  Tag:
    type: string
  Repo:
    type: resource
    operational_rule:
      steps:
      - direction: downstream
        resources:
          - aws:ecr_repo
  Context:
    type: string
  Dockerfile:
    type: string
classification:
  is: 
    - image
    - container
delete_context:
  requires_no_upstream: true
views:
  dataflow: small
