qualified_type_name: aws:ecr_image
properties:
  ImageName:
    type: string
  BaseImage:
    type: string
  Tag:
    type: string
  Repo:
    type: resource
    operational_rule:
      steps:
      - direction: downstream
        resources:
          - aws:ecr_repo
  Context:
    type: string
  Dockerfile:
    type: string
    operational_rule:
      if: |
        {{ eq (fieldValue "Dockerfile" .Self) "" }}
      steps:
      - direction: downstream
        resources:
          - docker:image:{{ .Self.Name }}
classification:
  is: 
    - image
    - container
delete_context:
  requires_no_upstream: true
views:
  dataflow: small
