qualified_type_name: aws:ecr_repo
display_name: ECR Repository

properties:
  ForceDelete:
    type: bool
    default_value: true
classification:
  is:
    - repository
delete_context:
  requires_no_upstream: true
views:
  dataflow: small


deployment_permissions:
  deploy: ["ecr:CreateRepository"]
  tear_down: ["ecr:DeleteRepository"]
  update: ["ecr:PutLifecyclePolicy"]