qualified_type_name: aws:ecr_repo
display_name: ECR Repository

properties:
  ForceDelete:
    type: bool
    default_value: true
  aws:tags:
    type: model

classification:
  is:
    - repository
delete_context:
  requires_no_upstream: true
views:
  dataflow: small

deployment_permissions:
  deploy:
    [
      'ecr:*Repository',
      'ecr:Get*',
      'ecr:TagResource',
      'ecr:Describe*',
      'ecr:List*',
      'ecr:*RepositoryPolicy',
    ]
  tear_down: ['kms:RetireGrant']
