qualified_type_name: aws:efs_mount_target
display_name: EFS Mount Target

properties:
  FileSystem:
    type: resource(aws:efs_file_system)
    namespace: true
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:efs_file_system
    description: The file system to which the mount target is attached
  Subnet:
    type: resource(aws:subnet)
    operational_rule:
      step:
        direction: downstream
        resources:
          - selector: aws:subnet
            properties:
              Type: private
          - aws:subnet
    description: The subnet in which to create the mount target
  SecurityGroups:
    type: list(resource(aws:security_group))
    operational_rule:
      step:
        direction: upstream
        resources:
          - aws:security_group
        unique: true
    description: One or more security groups that are associated with the mount target
  IpAddress:
    type: string

    description: The IP address at which the file system may be mounted via the mount
      target
path_satisfaction:
  as_target:
    - classification: network
      property_reference: Subnet#AvailabilityZone
      validity: downstream

classification:
  is:
    - efs_access

views:
  dataflow: small


deployment_permissions:
  deploy: ["efs:CreateMountTarget"]
  tear_down: ["efs:DeleteMountTarget"]
  update: ["efs:CreateMountTarget"]