qualified_type_name: aws:eks_node_group
display_name: EKS Node Group

properties:
  Cluster:
    type: resource(aws:eks_cluster)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:eks_cluster
  NodeRole:
    type: resource(aws:iam_role)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:iam_role
        unique: true
  Subnets:
    type: list(resource(aws:subnet))
    operational_rule:
      step:
        direction: downstream
        resources:
          - selector: aws:subnet
            properties:
              Type: private
          - aws:subnet
        num_needed: 2
  AmiType:
    type: string
    default_value: AL2_x86_64
  DesiredSize:
    type: int
    default_value: 2
  MinSize:
    type: int
    default_value: 1
  MaxSize:
    type: int
    default_value: 3
  MaxUnavailable:
    type: int
    default_value: 1
  DiskSize:
    type: int
    default_value: 20
  InstanceTypes:
    type: list(string)
    default_value:
      - t3.medium
  Labels:
    type: map(string,string)

classifications:
  is:
    - kubernetes
    - nodes
delete_context:
  requires_no_upstream: true
views:
  dataflow: small
