qualified_type_name: aws:eks_add_on
display_name: EKS AddOn

properties:
  AddOnName:
    type: string
    description: The name of the EKS AddOn to associate with the EKS cluster
  Cluster:
    type: resource(aws:eks_cluster)
    default_value: '{{ downstream "aws:eks_cluster" .Self }}'
    description: An EKS Cluster resource to which the AddOn will be attached
  Role:
    type: resource(aws:iam_role)
    description: An IAM role that provides permissions to the EKS AddOn for making
      AWS API calls
  aws:tags:
    type: model
    
delete_context:
  requires_no_upstream: true
views:
  dataflow: small


aws:eks_add_on:
  deploy: ["eks:CreateAddon"]
  tear_down: ["eks:DeleteAddon"]
  update: ["eks:UpdateAddon"]