qualified_type_name: aws:eks_cluster
display_name: EKS Cluster

properties:
  ClusterRole:
    type: resource(aws:iam_role)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:iam_role:ClusterRole-{{ .Self.Name }}
        unique: true
  Vpc:
    type: resource(aws:vpc)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:vpc
  Subnets:
    type: list(resource(aws:subnet))
    operational_rule:
      step:
        direction: downstream
        num_needed: 2
        resources:
          - selector: aws:subnet
  SecurityGroups:
    type: list(resource(aws:security_group))
    operational_rule:
      step:
        direction: upstream
        resources:
          - aws:security_group
        unique: true
  KubeConfig:
    type: resource(kubernetes:kube_config)
    operational_rule:
      step:
        direction: upstream
        resources:
          - kubernetes:kube_config
        unique: true
  Name:
    type: string
    configuration_disabled: true
    deploy_time: true
  ClusterEndpoint:
    type: string
    configuration_disabled: true
    deploy_time: true
  CertificateAuthorityData:
    type: string
    configuration_disabled: true
    deploy_time: true
  ClusterSecurityGroup:
    type: string
    configuration_disabled: true
    deploy_time: true

classification:
  is:
    - cluster
    - kubernetes

delete_context:
  requires_no_upstream: true
views:
  dataflow: parent
