qualified_type_name: aws:eks_cluster
display_name: EKS Cluster

properties:
  Version:
    type: string
    default_value: "1.28"
    description: The Kubernetes version to use for the EKS cluster
  ClusterRole:
    type: resource(aws:iam_role)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:iam_role:ClusterRole-{{ .Self.Name }}
        unique: true
    description: Defines an AWS IAM Role used by the EKS cluster to create AWS resources
      like EC2 instances for worker nodes
  Vpc:
    type: resource(aws:vpc)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:vpc
    description: Specifies the VPC the EKS cluster is deployed to
  Subnets:
    type: list(resource(aws:subnet))
    operational_rule:
      step:
        direction: downstream
        num_needed: 2
        resources:
          - selector: aws:subnet
    description: Defines a list of subnets within the VPC where the EKS cluster should
      be deployed
  SecurityGroups:
    type: list(resource(aws:security_group))
    operational_rule:
      step:
        direction: upstream
        resources:
          - aws:security_group
        unique: true
    description: Lists the security groups associated with the EKS cluster nodes
  Name:
    type: string
    configuration_disabled: true
    deploy_time: true
  ClusterEndpoint:
    type: string
    configuration_disabled: true
    deploy_time: true
  CertificateAuthorityData:
    type: string
    configuration_disabled: true
    deploy_time: true
  ClusterSecurityGroup:
    type: string
    configuration_disabled: true
    deploy_time: true

classification:
  is:
    - cluster
    - kubernetes

delete_context:
  requires_no_upstream: true
views:
  dataflow: parent


deployment_permissions:
  deploy: ["eks:CreateCluster"]
  tear_down: ["eks:DeleteCluster"]
  update: ["eks:UpdateCluster"]