qualified_type_name: aws:elasticache_cluster
display_name: ElastiCache Cluster

properties:
  Engine:
    type: string
    default_value: redis
    description: Specifies the in-memory data store or cache engine to be used by
      the cluster.
  CloudwatchGroup:
    type: resource(aws:log_group)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:log_group
        unique: true
    description: A reference to an AWS CloudWatch Log Group for logging purposes.
  SubnetGroup:
    type: resource(aws:elasticache_subnet_group)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:elasticache_subnet_group
    description: A subnet group to associate with the ElastiCache cluster for networking.
  SecurityGroups:
    type: list(resource(aws:security_group))
    operational_rule:
      step:
        direction: upstream
        resources:
          - aws:security_group
        unique: true
    description: A list of security group identifiers to control access to the ElastiCache
      cluster.
  NodeType:
    type: string
    default_value: cache.t2.micro
    description: The compute and memory capacity of the nodes in the node group (shard).
  NumCacheNodes:
    type: int
    default_value: 1
    description: The number of cache nodes that the cache cluster should have.
  aws:tags:
    type: model
  Port:
    type: int
    configuration_disabled: true
    deploy_time: true
    description: The port number on which each of the cache nodes accepts connections.
  CacheNodeAddress:
    type: string
    configuration_disabled: true
    deploy_time: true
    description: The endpoint address of a single node in the ElastiCache cluster.
  ClusterAddress:
    type: string
    configuration_disabled: true
    deploy_time: true
    description: The endpoint address of the ElastiCache cluster (memcached only).
path_satisfaction:
  as_target:
    - network

consumption:
  emitted:
    - model: EnvironmentVariables
      value:
        '{{ .Self.Name }}_EC_NODE_ADDR': '{{ fieldRef "CacheNodeAddress" .Self }}'
        '{{ .Self.Name }}_EC_ADDRESS': '{{ fieldRef "ClusterAddress" .Self }}'
        '{{ .Self.Name }}_EC_PORT': '{{ fieldRef "Port" .Self }}'

classification:
  is:
    - storage
    - redis
    - cache
    - memcached

delete_context:
  requires_no_upstream: true
  requires_no_downstream: true
views:
  dataflow: big


deployment_permissions:
  deploy: ["elasticache:CreateCacheCluster"]
  tear_down: ["elasticache:DeleteCacheCluster"]
  update: ["elasticache:ModifyCacheCluster"]