qualified_type_name: aws:elastic_ip
display_name: Elastic IP

classification:
  is:
    - static_ip_address

delete_context:
  requires_no_upstream: true
views:
  dataflow: small

deployment_permissions:
  deploy: ["ec2:AllocateAddress"]
  tear_down: ["ec2:ReleaseAddress"]
  update: ["ec2:AssociateAddress"]