qualified_type_name: aws:elastic_ip
display_name: Elastic IP

properties:
  aws:tags:
    type: model

classification:
  is:
    - static_ip_address

delete_context:
  requires_no_upstream: true
views:
  dataflow: small

deployment_permissions:
  deploy: ['ec2:*Address', 'ec2:*Addresses', 'ec2:*Tags']
