qualified_type_name: aws:iam_policy
display_name: IAM Policy

properties:
  Policy:
    type: map
    properties:
      Version:
        type: string
        default_value: '2012-10-17'
        description: Specifies the IAM Policy Language version
      Statement:
        type: list
        properties:
          Effect:
            type: string
            description: Whether the policy allows or denies access
          Action:
            type: list(string)
            description: Specifies the actions the policy allows or denies
          Resource:
            type: list(string)
            description: The AWS resource(s) upon which the actions will apply
          Principal:
            type: map
            properties:
              Service:
                type: list(string)
                description: The AWS service(s) allowed or denied access
              Federated:
                type: list(string)
                description: Federated users or roles that are allowed or denied access
              AWS:
                type: list(string)
                description: Specifies AWS account, user, or role to which the policy
                  is applied
            description: The account, user, role, or service to which the policy applies
          Condition:
            type: map
            properties:
              StringEquals:
                type: map(string,string)
                description: Condition that tests if a specified string is equal to
                  an expected string
              StringLike:
                type: map(string,string)
                description: Condition that tests if a specified string matches a
                  string pattern
              Null:
                type: map(string,string)
            description: Conditions for when the policy is in effect
        description: A list of individual statements that describe the details of
          the permission
    description: Defines the structure of the IAM policy in JSON format
  aws:tags:
    type: model
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true

path_satisfaction:
  as_target:
    - permissions

classification:
  is:
    - policy
    - security
    - permissions
  gives:
    - permissions

delete_context:
  requires_no_upstream_or_downstream: true

views:
  dataflow: small

deployment_permissions:
  deploy: ["iam:CreatePolicy"]
  tear_down: ["iam:DeletePolicy"]
  update: ["iam:CreatePolicyVersion"]