qualified_type_name: aws:iam_role
display_name: IAM Role
sanitize_name:
  # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints
  # Identifiers have these naming constraints:
  # - Must contain 1–63 alphanumeric characters or hyphens.
  # - First character must be a letter.
  # - Can't end with a hyphen or contain two consecutive hyphens.
  # - Must be unique for all DB instances per AWS account, per AWS Region.
  |
  {{ . 
    | length 1 55
  }}

properties:
  AssumeRolePolicyDoc:
    type: map
    properties:
      Version:
        type: string
        default_value: '2012-10-17'
      Statement:
        type: list
        properties:
          Effect:
            type: string
          Action:
            type: list(string)
          Resource:
            type: list(string)
          Principal:
            type: map
            properties:
              Service:
                type: list(string)
              Federated:
                type: list(string)
              AWS:
                type: list(string)
          Condition:
            type: map
            properties:
              StringEquals:
                type: map(string,string)
              StringLike:
                type: map(string,string)
              Null:
                type: map(string,string)
  ManagedPolicies:
    type: set(string)
  InlinePolicies:
    type: list
    properties:
      Name:
        type: string
      Policy:
        type: map
        properties:
          Version:
            type: string
          Statement:
            type: list
            properties:
              Effect:
                type: string
                default_value: Allow
              Action:
                type: list(string)
              Resource:
                type: list(string)
              Principal:
                type: map
                properties:
                  Service:
                    type: list(string)
                  Federated:
                    type: list(string)
                  AWS:
                    type: list(string)
              Condition:
                type: map
                properties:
                  StringEquals:
                    type: map(string,string)
                  StringLike:
                    type: map(string,string)
                  Null:
                    type: map(string,string)
  aws:tags:
    type: model
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true

classification:
  is:
    - role
    - permissions
  gives:
    - permissions
    - security

delete_context:
  requires_no_upstream: true
views:
  dataflow: small

deployment_permissions:
  deploy:
    # Note: don't use '*Role' here - PassRole with '*' resource is flagged in AWS as a security risk
    [
      'iam:CreateRole',
      'iam:GetRole*',
      'iam:PutRole*',
      'iam:TagRole',
      'iam:*RolePolicy',
      'iam:List*',
    ]
  tear_down: ['iam:DeleteRole*']
  update: ['iam:UntagRole', 'iam:Update*']
