qualified_type_name: aws:iam_oidc_provider
display_name: IAM OIDC Provider

properties:
  ClientIdLists:
    type: list(string)
    description: A list of client IDs (also referred to as audiences) that ID tokens
      are expected to be issued for.
  Cluster:
    type: resource(aws:eks_cluster)
    default_value: '{{ downstream "aws:eks_cluster" .Self }}'
    description: An Amazon EKS cluster resource to associate with the IAM OIDC provider.
  Region:
    type: resource(aws:region)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:region
    description: The AWS region in which to establish the IAM OIDC provider.
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true
  Sub:
    type: string
    configuration_disabled: true
    deploy_time: true
  Aud:
    type: string
    configuration_disabled: true
    deploy_time: true
classification:
  is:
    - authorization
  gives:
    - iam_access

delete_context:
  requires_no_upstream: true
views:
  dataflow: small
