qualified_type_name: aws:iam_policy

properties:
  Policy:
    type: map
    properties:
      Version:
        type: string
        default_value: '2012-10-17'
      Statement:
        type: list
        properties:
          Effect:
            type: string
          Action:
            type: list(string)
          Resource:
            type: list(string)
          Principal:
            type: map
            properties:
              Service:
                type: list(string)
              Federated:
                type: list(string)
              AWS:
                type: list(string)
          Condition:
            type: map
            properties:
              StringEquals:
                type: map(string,string)
              StringLike:
                type: map(string,string)
              Null:
                type: map(string,string)
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true

classification:
  is:
    - policy
    - security
  gives:
    - permissions

delete_context:
  requires_no_upstream_or_downstream: true

views:
  dataflow: small