qualified_type_name: aws:internet_gateway
display_name: Internet Gateway

properties:
  Vpc:
    type: resource(aws:vpc)
    namespace: true
    required: true
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:vpc
  Id:
    type: string
    configuration_disabled: true
    deployTime: true
  aws:tags:
    type: model

classification:
  gives:
    - internet_access

delete_context:
  requires_no_upstream: true
views:
  dataflow: small

deployment_permissions:
  deploy: ['ec2:*InternetGateway', 'ec2:Describe*']
