qualified_type_name: aws:internet_gateway
display_name: Internet Gateway

properties:
  Vpc:
    type: resource
    namespace: true
    required: true
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - aws:vpc

classification:
  gives:
    - internet_access

delete_context:
  requires_no_upstream: true
views:
  dataflow: small
