qualified_type_name: aws:internet_gateway
display_name: Internet Gateway

properties:
  Vpc:
    type: resource(aws:vpc)
    namespace: true
    required: true
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:vpc
  aws:tags:
    type: model

classification:
  gives:
    - internet_access

delete_context:
  requires_no_upstream: true
views:
  dataflow: small

deployment_permissions:
  deploy: ["ec2:CreateInternetGateway"]
  tear_down: ["ec2:DeleteInternetGateway"]
  update: ["ec2:AttachInternetGateway"]