qualified_type_name: aws:lambda_permission
display_name: Lambda Permission

properties:
  Function:
    type: resource(aws:lambda_function)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:lambda_function
  Principal:
    type: string
  Action:
    type: string
  Source:
    type: string

classification:
  is:
    - permissions

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small


deployment_permissions:
  deploy: ["lambda:AddPermission"]
  tear_down: ["lambda:RemovePermission"]
  update: ["lambda:AddPermission"]