qualified_type_name: aws:listener_certificate
display_name: Listener Certificate

properties:
  Certificate:
    type: resource(aws:acm_certificate)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:acm_certificate
    required: true
    description: Reference to an AWS ACM certificate resource used to enable TLS on
      a load balancer listener.
  Listener:
    type: resource(aws:load_balancer_listener)
    required: true

    description: Reference to an AWS load balancer listener resource where the certificate
      will be attached.
delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small

deployment_permissions:
  deploy: ['elasticloadbalancing:AddListenerCertificates']
  tear_down: ['elasticloadbalancing:RemoveListenerCertificates']
  update: ['elasticloadbalancing:AddListenerCertificates']
