qualified_type_name: aws:load_balancer
display_name: Load Balancer

properties:
  IpAddressType:
    type: string
  LoadBalancerAttributes:
    type: map(string,string)
  Scheme:
    type: string
    default_value: internal
  SecurityGroups:
    type: list(resource(aws:security_group))
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - aws:security_group
  Subnets:
    type: list(resource(aws:subnet))
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - selector: aws:subnet
              properties:
                Type: private
            - aws:subnet
  Tags:
    type: map(string,string)
  Type:
    type: string
    default_value: network
  NlbUri:
    type: string
    configuration_disabled: true
    deploy_time: true

path_satisfaction:
  as_target:
    - network

classification:
  is:
    - load_balancer
    - scalable
    - reliable

delete_context:
  requires_no_downstream: true
views:
  dataflow: big
