qualified_type_name: aws:load_balancer
display_name: Load Balancer
sanitize_name:
  # https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateLoadBalancer.html
  # This name must be unique per region per account,
  # can have a maximum of 32 characters (24 since we reserve 8 for an IaC-appended suffix),
  # must contain only alphanumeric characters or hyphens,
  # must not begin or end with a hyphen,
  # and must not begin with "internal-".
  |
  {{ . 
    | replace `^internal-` ""
    | replace `(^-)|(-$)` ""
    | replace `[^[:alnum:]-]+` "-"
    | length 1 24
  }}

properties:
  IpAddressType:
    type: string
  LoadBalancerAttributes:
    type: map(string,string)
  Scheme:
    type: string
    default_value: internal
  SecurityGroups:
    type: list(resource(aws:security_group))
    operational_rule:
      steps:
        - direction: upstream
          resources:
            - aws:security_group
          unique: true
  Subnets:
    type: list(resource(aws:subnet))
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - selector: aws:subnet
              properties:
                Type: private
            - aws:subnet
          num_needed: 2
  Tags:
    type: map(string,string)
  Type:
    type: string
    default_value: network
  NlbUri:
    type: string
    configuration_disabled: true
    deploy_time: true

path_satisfaction:
  as_target:
    - network
    - network#Subnets
  as_source:
    - network#Subnets
    - target_group

classification:
  is:
    - load_balancer
    - scalable
    - reliable

delete_context:
  requires_no_downstream: true
views:
  dataflow: big
