qualified_type_name: aws:load_balancer_listener_rule
display_name: Listener Rule

properties:
  Actions:
    type: list(model(aws:load_balancer_listener:action))
  Conditions:
    type: list(map)
    max_length: 5
    properties:
      HostHeader:
        type: map
        properties:
          Values:
            type: list(string)
      HttpHeader:
        type: map
        properties:
          HttpHeaderName:
            type: string
          Values:
            type: list(string)
      HttpRequestMethod:
        type: map
        properties:
          Values:
            type: list(string)
      PathPattern:
        type: map
        properties:
          Values:
            type: list(string)
      QueryString:
        type: map
        properties:
          Values:
            type: list(map)
            properties:
              Key:
                type: string
              Value:
                type: string
      SourceIp:
        type: map
        properties:
          Values:
            type: list(string)
  Listener:
    type: resource(aws:load_balancer_listener)
    namespace: true
    operational_rule:
      step:
        direction: upstream
        resources:
          - aws:load_balancer_listener
  Priority:
    type: int
    required: true
    min_value: 1
    max_value: 50000
    default_value: 1
  Tags:
    type: map(string,string)
  aws:tags:
    type: model

delete_context:
  requires_no_upstream: true
views:
  dataflow: big

classification:
  is:
    - listener_rule

path_satisfaction:
  as_source:
    - network#Listener#LoadBalancer#Subnets

deployment_permissions:
  deploy: ['elasticloadbalancing:CreateRule']
  tear_down: ['elasticloadbalancing:DeleteRule']
  update: ['elasticloadbalancing:ModifyRule']
