qualified_type_name: aws:log_group
display_name: CloudWatch Log Group

properties:
  LogGroupName:
    type: string
    description: The name of the log group.
  RetentionInDays:
    type: int
    default_value: 5
    description: The number of days to retain the log events in the specified log
      group.
  aws:tags:
    type: model
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true

classification:
  is:
    - logs
    - monitoring

path_satisfaction:
  as_target:
    - network
    - permissions

delete_context:
  requires_no_upstream: true
  requires_no_downstream: true

views:
  dataflow: small
