qualified_type_name: aws:log_group
display_name: CloudWatch Log Group

properties:
  LogGroupName:
    type: string
  RetentionInDays:
    type: int
    default_value: 5

classification:
  is:
    - logs
    - monitoring

delete_context:
  requires_no_upstream: true
  requires_no_downstream: true

views:
  dataflow: small
