qualified_type_name: aws:nat_gateway
display_name: NAT Gateway

properties:
  ElasticIp:
    type: resource(aws:elastic_ip)
    required: true
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:elastic_ip
        unique: true
    description: The Elastic IP address to associate with the NAT Gateway. An Elastic
      IP ensures that the NAT Gateway has a static IPv4 address.
  Subnet:
    type: resource(aws:subnet)
    required: true
    namespace: true
    operational_rule:
      step:
        direction: downstream
        resources:
          - selector: aws:subnet
            properties:
              Type: public
        selection_operator: spread
    description: The subnet in which to deploy the NAT Gateway. The subnet must be
      a public subnet.
  Id:
    type: string
    configuration_disabled: true
    deploy_time: true
  aws:tags:
    type: model

delete_context:
  requires_no_upstream: true
views:
  dataflow: small

deployment_permissions:
  deploy: ['ec2:*NatGateway*']
