qualified_type_name: aws:private_dns_namespace
display_name: Private DNS Namespace

properties:
  Vpc:
    type: resource(aws:vpc)
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - aws:vpc

classification:
  is:
    - service_discovery

delete_context:
  require_no_upstream: true

views:
  dataflow: small
