qualified_type_name: aws:private_dns_namespace
display_name: Private DNS Namespace

properties:
  Vpc:
    type: resource(aws:vpc)
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:vpc
  Id:
    type: string
    deploy_time: true
    configuration_disabled: true

path_satisfaction:
  as_target:
    - permissions

classification:
  is:
    - service_discovery

delete_context:
  requires_no_upstream: true

views:
  dataflow: small
