qualified_type_name: aws:rds_instance
display_name: RDS Instance
sanitize_name:
  # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints
  # Identifiers have these naming constraints:
  # - Must contain 1–63 alphanumeric characters or hyphens.
  # - First character must be a letter.
  # - Can't end with a hyphen or contain two consecutive hyphens.
  # - Must be unique for all DB instances per AWS account, per AWS Region.
  |
  {{ . 
    | replace `^[^[:alpha:]]+` "" 
    | replace `--+` "-" 
    | replace `-$` ""
    | replace `[^[:alnum:]-]+` "-"
    | length 1 63
  }}

properties:
  SubnetGroup:
    type: resource(aws:rds_subnet_group)
    operational_rule:
      steps:
        - direction: downstream
          resources:
            - aws:rds_subnet_group
  SecurityGroups:
    type: list(resource(aws:security_group))
    operational_rule:
      steps:
        - direction: upstream
          resources:
            - aws:security_group
          unique: true
  DatabaseName:
    type: string
    default_value: '{{ .Self.Name }}'
  IamDatabaseAuthenticationEnabled:
    type: bool
    default_value: true
  Username:
    type: string
    configuration_disabled: true
  Password:
    type: string
    configuration_disabled: true
  Engine:
    type: string
    default_value: postgres
  EngineVersion:
    type: string
    default_value: '13.7'
  InstanceClass:
    type: string
    default_value: db.t3.micro
  SkipFinalSnapshot:
    type: bool
    default_value: true
  AllocatedStorage:
    type: int
    default_value: 20
  CredentialsSecretValue:
    type: string
    configuration_disabled: true
    deploy_time: true
  RdsConnectionArn:
    type: string
    configuration_disabled: true
    deploy_time: true
  Endpoint:
    type: string
    configuration_disabled: true
    deploy_time: true

classification:
  is:
    - storage
    - sql
    - database
    - relational

path_satisfaction:
  as_target:
    - network#SubnetGroup#Subnets
    - network
    - permissions

delete_context:
  requires_no_upstream: true
  requires_explicit_delete: true
views:
  dataflow: big
