qualified_type_name: aws:rds_subnet_group
display_name: RDS Subnet Group
sanitize_name:
  # https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Limits.html#RDS_Limits.Constraints
  # These names have these constraints:
  # - Must contain 1–255 alphanumeric characters.
  # - Alphanumeric characters, spaces, hyphens, underscores, and periods are allowed
  |
  {{ . 
    | replace `[^[:alnum:] _.-]+` "-"
    | length 1 255
  }}

properties:
  Subnets:
    type: list(resource(aws:subnet))
    operational_rule:
      step:
        direction: downstream
        num_needed: 2
        resources:
          - selector: aws:subnet
            properties:
              Type: private
          - aws:subnet
    description: A list of subnets for the RDS subnet group, with at least 2 needed,
      and all subnets need to be of 'private' type
  aws:tags:
    type: model

    description: A map of key-value pairs to assign as tags to the RDS subnet group
delete_context:
  requires_no_upstream: true
views:
  dataflow: small

deployment_permissions:
  deploy: ["rds:CreateDBSubnetGroup"]
  tear_down: ["rds:DeleteDBSubnetGroup"]
  update: ["rds:ModifyDBSubnetGroup"]