qualified_type_name: aws:rds_subnet_group
display_name: RDS Subnet Group

properties:
  Subnets:
    type: list(resource(aws:subnet))
    operational_rule:
      steps:
        - direction: downstream
          num_needed: 2
          resources:
            - selector: aws:subnet
              properties:
                Type: private
            - aws:subnet
  Tags:
    type: map(string,string)

delete_context:
  requires_no_upstream: true
views:
  dataflow: small
