qualified_type_name: aws:rest_api
display_name: API Gateway V1 (REST API)
sanitize_name: |
  {{ . | replace `[^a-zA-Z0-9_-]+` "-" | length 3 64 }}

properties:
  BinaryMediaTypes:
    type: list(string)
    default_value:
      - application/octet-stream
      - image/*
  ChildResources:
    type: string
    configuration_disabled: true
    deploy_time: true

path_satisfaction:
  as_source:
    - api_route
  as_target:
    - api_stage

classification:
  is:
    - serverless
    - api
    - highly_available
    - scalable
    - reliable

delete_context:
  requires_no_upstream: true
  requires_no_downstream: true
  requires_explicit_delete: true

views:
  dataflow: parent
