qualified_type_name: aws:route_table
display_name: Route Table

properties:
  Vpc:
    type: resource(aws:vpc)
    required: true
    namespace: true
    operational_rule:
      step:
        direction: downstream
        resources:
          - aws:vpc
    description: Specifies the Virtual Private Cloud (VPC) where the route table is
      deployed.
  Routes:
    type: list
    properties:
      CidrBlock:
        type: string
        description: The IP address range, in CIDR notation, applicable for the routing
          rule.
      NatGateway:
        type: resource(aws:nat_gateway)
        description: A reference to a NAT gateway resource to which traffic is directed.
      Gateway:
        type: resource(aws:internet_gateway)

        description: A reference to an internet gateway resource to which traffic
          is directed.
    description: Defines a list of routing rules for directing network traffic.
delete_context:
  requires_no_upstream: true
views:
  dataflow: small

deployment_permissions:
  deploy: ["ec2:CreateRouteTable"]
  tear_down: ["ec2:DeleteRouteTable"]
  update: ["ec2:ReplaceRouteTableAssociation"]