qualified_type_name: aws:s3_bucket
display_name: S3 Bucket
sanitize_name:
  # https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
  # Identifiers have these naming constraints:
  # - Must contain 1–63 alphanumeric characters or hyphens (55 since we reserve 8 for an IaC-appended suffix).
  # - First character must be a letter.
  # - Can't end with a hyphen or contain two consecutive hyphens.
  # - Names can consist only of lowercase letters, numbers, dots (.), and hyphens (-).
  |
  {{ . 
    | replace `^[^[:alpha:]]+` "" 
    | replace `--+` "-" 
    | replace `-$` ""
    | replace `_` "-"
    | replace `[^[:alnum:]-]+` "-"
    | length 1 55
  }}


properties:
  ForceDestroy:
    type: bool
    default_value: true
  IndexDocument:
    type: string
  AllBucketDirectory:
    type: string
    configuration_disabled: true
    deploy_time: true
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true
  BucketRegionalDomainName:
    type: string
    configuration_disabled: true
    deploy_time: true
  BucketName:
    type: string
    configuration_disabled: true
    deploy_time: true
  SSEAlgorithm:
    type: string
    default_value: aws:kms

has_service_api: true
path_satisfaction:
  as_target:
    - network
    - permissions

classification:
  is:
    - storage
    - blob
    - cloudfront_origin

delete_context:
  requires_no_upstream: true
  requires_no_downstream: true
  requires_explicit_delete: true

views:
  dataflow: big
