qualified_type_name: aws:s3_bucket
display_name: S3 Bucket
sanitize_name:
  # https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
  |
  {{ . 
    | replace `^(xn--)|sthree-)|(sthree-configurator)` ""
    | replace `(-s3alias)|(--ol-s3)$` ""
    | replace `[^a-z0-9.-]+` "-"
    | replace `(^[.-]+)|([.-]+$)` ""
    | replace `\.\.+` "."
    | replace `^([0-9]+)\.([0-9]+)\.([0-9]+)` "$1-$2-$3"
    | length 3 63
  }}

properties:
  ForceDestroy:
    type: bool
    default_value: true
  IndexDocument:
    type: string
  AllBucketDirectory:
    type: string
    configuration_disabled: true
    deploy_time: true
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true
  BucketRegionalDomainName:
    type: string
    configuration_disabled: true
    deploy_time: true
  BucketName:
    type: string
    configuration_disabled: true
    deploy_time: true
  SSEAlgorithm:
    type: string
    default_value: aws:kms

path_satisfaction:
  as_target:
    - network
    - permissions

consumption:
  emitted:
    - model: EnvironmentVariables
      value:
        '{{ .Self.Name }}_BUCKET_NAME': '{{ fieldRef "BucketName" .Self }}'


classification:
  is:
    - storage
    - blob
    - cloudfront_origin

delete_context:
  requires_no_upstream: true
  requires_no_downstream: true
  requires_explicit_delete: true

views:
  dataflow: big
