qualified_type_name: aws:secret_version
display_name: Secret Version

properties:
  Secret:
    type: resource(aws:secret)
    operational_rule:
      steps:
        - direction: upstream
          resources:
            - aws:secret
          unique: true
  Type:
    type: string
  Content:
    type: string
    configuration_disabled: true

delete_context:
  requires_no_upstream: true
views:
  dataflow: small
