qualified_type_name: aws:ses_email_identity
display_name: SES Email Identity

properties:
  EmailIdentity:
    type: string
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true

classification:
  is:
    - messaging
    - email

delete_context:
  require_no_upstream: true
views:
  dataflow: big
