qualified_type_name: aws:ses_email_identity
display_name: SES Email Identity

properties:
  EmailIdentity:
    type: string
    description: The email address or domain to be verified with Amazon SES for sending
      emails
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true

classification:
  is:
    - messaging
    - email

path_satisfaction:
  as_target:
    - network
    - permissions

delete_context:
  requires_no_upstream: true
views:
  dataflow: big
