qualified_type_name: aws:sqs_queue
display_name: SQS Queue

properties:
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true
  FifoQueue:
    type: bool
  DelaySeconds:
    type: int
  MaxMessageSize:
    type: int
  VisibilityTimeout:
    type: int
  Tags:
    type: map(string,string)

path_satisfaction:
  as_target:
    - network
    - permissions

classification:
  is:
    - queue

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: big
