qualified_type_name: aws:sqs_queue
display_name: SQS Queue

properties:
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true
  FifoQueue:
    type: bool
    description: Designates whether the queue is a FIFO queue
  DelaySeconds:
    type: int
    description: The time in seconds that the delivery of all messages in the queue
      is delayed
  MaxMessageSize:
    type: int
    description: The limit of how many bytes a message can contain before Amazon SQS
      rejects it
  VisibilityTimeout:
    type: int
    description: The period during which Amazon SQS prevents other consuming components
      from receiving and processing a message
  aws:tags:
    type: model

path_satisfaction:
  as_target:
    - network
    - permissions

classification:
  is:
    - queue
    - messaging

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: big
