qualified_type_name: aws:target_group
display_name: Target Group
sanitize_name:
  # https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html
  # This name must be unique per region per account,
  # can have a maximum of 32 characters (24 since we reserve 8 for an IaC-appended suffix),
  # must contain only alphanumeric characters or hyphens,
  # and must not begin or end with a hyphen.
  |
  {{ . 
    | replace `[^[:alnum:]-]+` "-"
    | replace `(^-)|(-$)` ""
    | length 1 24
  }}

properties:
  Port:
    type: int
    default_value: 80
    min_value: 1
    max_value: 65535
  Protocol:
    type: string
    allowed_values:
      - GENEVE
      - HTTP
      - HTTPS
      - TCP
      - TCP_UDP
      - TLS
      - UDP
  Vpc:
    type: resource(aws:vpc)
    default_value: '{{ closestDownstream "aws:vpc" .Self }}'
  TargetType:
    type: string
    allowed_values:
      #      - alb # only valid for Network Load Balancers
      - instance
      - ip
      - lambda # only valid for Application Load Balancers
    description: |
      The type of target that you must specify when registering targets with this target group.
      'lambda` is only valid for Application Load Balancers.
  Targets:
    type: list
    properties:
      Id:
        type: string
      Port:
        type: int
        default_value: 80
        min_value: 1
        max_value: 65535
  HealthCheck:
    type: map
    important: true
    properties:
      Enabled:
        type: bool
        default_value: true
      Path:
        type: string
      Protocol:
        type: string
        default_value: '{{ fieldValue "Protocol" .Self }}'
        allowed_values:
          - HTTP
          - HTTPS
          - TCP
      Port:
        type: int
        min_value: 1
        max_value: 65535
      Interval:
        type: int
        default_value: 30
      Timeout:
        type: int
        default_value: 5
      HealthyThreshold:
        type: int
        default_value: 5
      UnhealthyThreshold:
        type: int
        default_value: 2
      Matcher:
        type: string
  LambdaMultiValueHeadersEnabled:
    type: bool
  aws:tags:
    type: model
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true
  Id:
    type: string
    description: The provider-assigned unique identifier for the target group, available after deployment
    configuration_disabled: true
    deploy_time: true
    required: true

classification:
  is:
    - target_group

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small

deployment_permissions:
  deploy: ['elasticloadbalancing:*TargetGroup*']
  update: ['elasticloadbalancing:Describe*']
