qualified_type_name: aws:target_group
display_name: Target Group
sanitize_name:
  # https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html
  # This name must be unique per region per account,
  # can have a maximum of 32 characters (24 since we reserve 8 for an IaC-appended suffix),
  # must contain only alphanumeric characters or hyphens,
  # and must not begin or end with a hyphen.
  |
  {{ . 
    | replace `[^[:alnum:]-]+` "-"
    | replace `(^-)|(-$)` ""
    | length 1 24
  }}

properties:
  Port:
    type: int
    default_value: 80
  Protocol:
    type: string
  Vpc:
    type: resource(aws:vpc)
    default_value: '{{ closestDownstream "aws:vpc" .Self }}'
  TargetType:
    type: string
  Targets:
    type: list
    properties:
      Id:
        type: string
      Port:
        type: int
        default_value: 80
  HealthCheck:
    type: map
    properties:
      Enabled:
        type: bool
        default_value: true
      Path:
        type: string
      Protocol:
        type: string
        default_value: '{{ fieldValue "Protocol" .Self }}'
      Port:
        type: int
        default_value: '{{ fieldValue "Port" .Self }}'
      Interval:
        type: int
        default_value: 30
      Timeout:
        type: int
        default_value: 5
      HealthyThreshold:
        type: int
        default_value: 5
      UnhealthyThreshold:
        type: int
        default_value: 2
      Matcher:
        type: string
        default_value: 200-299
  Arn:
    type: string
    configuration_disabled: true
    deploy_time: true

classification:
  is:
    - target_group

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small
