qualified_type_name: aws:vpc
display_name: VPC

properties:
  CidrBlock:
    type: string
    required: true
    default_value: '10.0.0.0/16'
    description: Specifies the IP address range for the VPC in CIDR notation
  EnableDnsSupport:
    type: bool
    default_value: true
    description: Determines whether DNS resolution is supported for the VPC
  EnableDnsHostnames:
    type: bool
    default_value: true
    description: Determines whether instances with public IP addresses get corresponding
      public DNS hostnames
  Id:
    type: string
    configuration_disabled: true
    deploy_time: true
    required: true

classification:
  is:
    - network
    - virtual_network
path_satisfaction:
  as_target:
    - network

delete_context:
  requires_no_upstream: true
views:
  dataflow: parent
