qualified_type_name: aws:vpc_link
display_name: VPC Link

properties:
  Target:
    type: resource(aws:load_balancer)
  aws:tags:
    type: model

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small
