provider: aws
type: api_deployment
rules:
- enforcement: exactly_one
  direction: downstream
  resource_types:
  - rest_api
  set_field: RestApi
  unsatisfied_action:
    operation: create
  rules:
  - enforcement: any_available
    direction: downstream
    resource_types:
    - api_method
    - api_integration
delete_context:
  requires_no_upstream: true