provider: aws
type: api_stage
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - rest_api
    set_field: RestApi
    unsatisfied_action:
      operation: create
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - api_deployment
    set_field: Deployment
    unsatisfied_action:
      operation: create
configuration:
  - field: StageName
    value: stage
delete_context:
  requires_no_upstream: true
views:
  dataflow: small