provider: aws
type: api_method
rules:
  - enforcement: exactly_one
    direction: upstream
    resources:
      - '{{ upstream "aws:rest_api" (downstream "aws:api_integration" .Self) }}'
    set_field: RestApi
    unsatisfied_action:
      operation: create
configuration:
  - field: HttpMethod
    value: ANY
  - field: Authorization
    value: NONE
delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small
