provider: aws
type: api_deployment
rules:
  - enforcement: exactly_one
    direction: downstream
    resources:
      - '{{ downstream "aws:rest_api" (upstream "aws:api_stage" .Self) }}'
    set_field: RestApi
    unsatisfied_action:
      operation: create
    rules:
      - enforcement: any_available
        direction: downstream
        resource_types:
          - api_method
          - api_integration
delete_context:
  requires_no_upstream: true
views:
  dataflow: small
