provider: aws
type: api_integration
rules:
  - enforcement: exactly_one
    direction: upstream
    resource_types:
      - api_method
    set_field: Method
    unsatisfied_action:
      operation: create
      unique: true
  - enforcement: exactly_one
    direction: upstream
    resource_types:
      - rest_api
    set_field: RestApi
    unsatisfied_action:
      operation: create
configuration:
  - field: IntegrationHttpMethod
    default_value: ANY
  - field: Route
    default_value: /
    steps:
      - object: '{{ upstream "aws:api_resource" }}'
        property: PathPart
      - object: '{{ upstream "aws:api_method" }}'
        property: RequestParameters
        value: '{{ split "/" .Value | filterMatch "^:\\w+$" | mapString ":(.*)" "method.request.path.$1" | keysToMapWithDefault "true" }}'
      - property: Route
        value: '{{ .Value }}'
      - object: '{{ self }}'
        property: RequestParameters
        value: |
          {{ $params := split "/" .Value | filterMatch "^:\\w+$" }}
          {{ zipToMap
            ($params | mapString ":(.*)" "integration.request.path.$1")
            ($params | mapString ":(.*)" "method.request.path.$1")
          }}

delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small
