provider: aws
type: ecr_image
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - ecr_repo
    set_field: Repo
    unsatisfied_action:
      operation: create
  - enforcement: exactly_one
    direction: downstream
    if: |
      {{ eq (fieldValue "Dockerfile" .Self) "" }}
    resources:
      - docker:image:{{ .Self.Name }}
    unsatisfied_action:
      operation: create
configuration:
  - field: ExtraOptions
    value:
      - --platform
      - linux/amd64
      - --quiet
  - field: BaseImage
  - field: Dockerfile
delete_context:
  requires_no_upstream: true
views:
  dataflow: small
