provider: aws
type: ecs_service
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - ecs_cluster
    set_field: Cluster
    unsatisfied_action:
      operation: create
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - ecs_task_definition
    set_field: TaskDefinition
    unsatisfied_action:
      operation: create
      unique: true
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - vpc
    remove_direct_dependency: true
    rules:
      - enforcement: any_available
        direction: downstream
        resource_types:
          - subnet_private
          - subnet_public
        set_field: Subnets
        unsatisfied_action:
          operation: create
          default_type: subnet_private
        num_needed: 2
      - enforcement: any_available
        direction: downstream
        resource_types:
          - security_group
        set_field: SecurityGroups
        num_needed: 1
        unsatisfied_action:
          operation: create
configuration:
  - field: LaunchType
    value: FARGATE
  - field: DesiredCount
    value: 1
  - field: ForceNewDeployment
    value: true
delete_context:
  requires_no_upstream: true
  requires_no_downstream: true
  requires_explicit_delete: true
views:
  dataflow: big
