provider: aws
type: efs_mount_target
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - efs_file_system
    set_field: FileSystem
    unsatisfied_action:
      operation: create
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - vpc
    remove_direct_dependency: true
    rules:
      - enforcement: exactly_one
        direction: downstream
        resource_types:
          - subnet_private
          - subnet_public
        set_field: Subnet
        unsatisfied_action:
          operation: create
          default_type: subnet_private
      - enforcement: any_available
        direction: downstream
        resource_types:
          - security_group
        set_field: SecurityGroups
        num_needed: 1
        unsatisfied_action:
          operation: create
views:
  dataflow: small