provider: aws
type: efs_access_point
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - efs_file_system
    set_field: FileSystem
    unsatisfied_action:
      operation: create
configuration:
  - field: PosixUser
    value:
      Gid: 1000
      Uid: 1000
  - field: RootDirectory
    value:
      CreationInfo:
        OwnerGid: 1000
        OwnerUid: 1000
        Permissions: '777'
      Path: /mnt/efs
delete_context:
  requires_no_upstream: true
  requires_no_downstream: false
  requires_explicit_delete: false
views:
  dataflow: small