provider: aws
type: efs_file_system
configuration:
  - field: Encrypted
    value: true
  - field: PerformanceMode
    value: generalPurpose
  - field: ThroughputMode
    value: bursting

delete_context:
  requires_no_upstream: true
  requires_no_downstream: true
  requires_explicit_delete: true
views:
  dataflow: big
