provider: aws
type: eks_cluster
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - iam_role
    set_field: ClusterRole
    unsatisfied_action:
      operation: create
      unique: true
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - vpc
    set_field: Vpc
    unsatisfied_action:
      operation: create
    rules:
      - enforcement: any_available
        direction: downstream
        resource_types:
          - subnet_private
        set_field: Subnets
        unsatisfied_action:
          operation: create
        num_needed: 2
      - enforcement: any_available
        direction: downstream
        resource_types:
          - subnet_public
        set_field: Subnets
        unsatisfied_action:
          operation: create
        num_needed: 2
      - enforcement: any_available
        direction: downstream
        resource_types:
          - security_group
        num_needed: 1
        set_field: SecurityGroups
        unsatisfied_action:
          operation: create
          unique: true
  - enforcement: any_available
    direction: upstream
    resource_types:
      - eks_node_group
    num_needed: 1
    unsatisfied_action:
      operation: create
      unique: true
  - enforcement: exactly_one
    direction: upstream
    classifications:
      - kubeconfig
    set_field: Kubeconfig
    unsatisfied_action:
      operation: create
      unique: true
delete_context:
  requires_no_upstream: true
views:
  dataflow: parent