provider: aws
type: iam_oidc_provider
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - eks_cluster
    set_field: Cluster
    unsatisfied_action:
      operation: create
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - region
    set_field: Region
    unsatisfied_action:
      operation: create
delete_context:
  requires_no_upstream: true
views:
  dataflow: small
