provider: aws
type: internet_gateway
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - vpc
    set_field: Vpc
    unsatisfied_action:
      operation: create
delete_context:
  requires_no_upstream: true
views:
  dataflow: small
