provider: aws
type: kinesis_stream_consumer
rules:
  - enforcement: exactly_one
    direction: upstream
    resource_types:
      - kinesis_stream
    set_field: Stream
    unsatisfied_action:
      operation: error
delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small