provider: aws
type: load_balancer_listener
rules:
  - enforcement: exactly_one
    direction: upstream
    resource_types:
      - load_balancer
    set_field: LoadBalancer
    unsatisfied_action:
      operation: error
delete_context:
  requires_no_upstream_or_downstream: true
views:
  dataflow: small