provider: aws
type: private_dns_namespace
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - vpc
    set_field: Vpc
    unsatisfied_action:
      operation: create
views:
  dataflow: small