provider: aws
type: rds_instance
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - vpc
    remove_direct_dependency: true
    rules:
      - enforcement: exactly_one
        direction: downstream
        resource_types:
          - rds_subnet_group
        set_field: SubnetGroup
        unsatisfied_action:
          operation: create
      - enforcement: any_available
        direction: downstream
        resource_types:
          - security_group
        set_field: SecurityGroups
        num_needed: 1
        unsatisfied_action:
          operation: create
configuration:
  - field: Engine
    value: postgres
  - field: EngineVersion
    value: '13.7'
  - field: InstanceClass
    value: db.t4g.micro
  - field: AllocatedStorage
    value: 20
  - field: IamDatabaseAuthenticationEnabled
    value: true
  - field: SkipFinalSnapshot
    value: true
delete_context:
  requires_no_upstream: true
  requires_explicit_delete: true
views:
  dataflow: big
