provider: aws
type: rest_api
rules:
  - enforcement: any_available
    direction: upstream
    resource_types:
      - api_stage
    num_needed: 1
    unsatisfied_action:
      operation: create
      unique: true
configuration:
  - field: BinaryMediaTypes
    value:
      - application/octet-stream
      - image/*
delete_context:
  requires_no_upstream: true
  requires_no_downstream: true
  requires_explicit_delete: true
views:
  dataflow: big
