provider: aws
type: route_table
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - vpc
    set_field: Vpc
    unsatisfied_action:
      operation: create
  - enforcement: conditional
    direction: upstream
    resource_types:
      - subnet_private
    rules:
      - enforcement: exactly_one
        direction: downstream
        resource_types:
          - nat_gateway
        unsatisfied_action:
          operation: create
          unique: true
        no_parent_dependency: true
  - enforcement: conditional
    direction: upstream
    resource_types:
      - subnet_public
    rules:
      - enforcement: exactly_one
        direction: downstream
        resource_types:
          - internet_gateway
        unsatisfied_action:
          operation: create
        no_parent_dependency: true
delete_context:
  requires_no_upstream: true
views:
  dataflow: small