provider: aws
type: route53_record
rules:
  - enforcement: exactly_one
    direction: downstream
    resource_types:
      - route53_hosted_zone
    set_field: Zone
    unsatisfied_action:
      operation: error
delete_context:
  requires_no_downstream: true
views:
  dataflow: small
