provider: aws
type: secret_version
rules:
  - enforcement: exactly_one
    direction: upstream
    resource_types:
      - secret
    set_field: Secret
    unsatisfied_action:
      operation: create
      unique: true
delete_context:
  requires_no_upstream: true
views:
  dataflow: small