source: kubernetes:deployment
target: aws:private_dns_namespace
operational_rules:
  - steps:
      - resource: '{{ downstream "aws:iam_role" .Source }}'
        direction: downstream
        resources:
          - '{{ .Target }}'
