name: kubernetes:ObjectMeta
properties:
  Name:
    type: string
  Namespace:
    type: resource(kubernetes:namespace)
  Labels:
    type: map(string,string)
  Annotations:
    type: map(string,string)
