name: kubernetes:PodSpec
properties:
  volumes:
    type: list
    properties:
      name:
        type: string
      volumeSource:
        type: map
        properties:
          persistentVolumeClaim:
            type: map
            properties:
              claimName:
                type: string
              readOnly:
                type: bool
  containers:
    type: list(model(kubernetes:Container))
    default_value:
      - name: '{{ .Self.Name }}'
  nodeSelector:
    type: map(string,string)
  serviceAccountName:
    type: resource(kubernetes:service_account)
    operational_rule:
      step:
        direction: downstream
        resources:
          - kubernetes:service_account:{{ .Self.Name }}
        unique: true
  automountServiceAccountToken:
    type: bool
    default_value: true