name: kubernetes:VolumeMount
properties:
  name:
    type: string
  readOnly:
    type: bool
  mountPath:
    type: string
  subPath:
    type: string
  mountPropagation:
    type: string
  subPathExpr:
    type: string
