package resources

import (
	"github.com/klothoplatform/klotho/pkg/core"
	"github.com/klothoplatform/klotho/pkg/infra/kubernetes"
)

func ListAll() []core.Resource {
	return []core.Resource{
		&AccountId{},
		&ApiDeployment{},
		&AMI{},
		&ApiIntegration{},
		&ApiMethod{},
		&ApiResource{},
		&ApiStage{},
		&AvailabilityZones{},
		&CloudfrontDistribution{},
		&DynamodbTable{},
		&EcrImage{},
		&EcrRepository{},
		&Ec2Instance{},
		&EksAddon{},
		&EksCluster{},
		&EksFargateProfile{},
		&EksNodeGroup{},
		&ElasticIp{},
		&ElasticacheCluster{},
		&ElasticacheSubnetgroup{},
		&IamPolicy{},
		&IamRole{},
		&InstanceProfile{},
		&InternetGateway{},
		&LambdaFunction{},
		&LambdaPermission{},
		&Listener{},
		&LoadBalancer{},
		&LogGroup{},
		&NatGateway{},
		&OpenIdConnectProvider{},
		&OriginAccessIdentity{},
		&PrivateDnsNamespace{},
		&RdsInstance{},
		&RdsProxyTargetGroup{},
		&RdsProxy{},
		&RdsSubnetGroup{},
		&Region{},
		&RestApi{},
		&RolePolicyAttachment{},
		&RouteTable{},
		&S3BucketPolicy{},
		&S3Bucket{},
		&S3Object{},
		&SecretVersion{},
		&Secret{},
		&SecurityGroup{},
		&Subnet{Vpc: &Vpc{}},
		&TargetGroup{},
		&VpcEndpoint{},
		&VpcLink{},
		&Vpc{},
		&kubernetes.HelmChart{},
		&kubernetes.HelmChart{},
		&kubernetes.Kubeconfig{},
		&kubernetes.KustomizeDirectory{},
		&kubernetes.Manifest{},
	}
}
