source: kubernetes:deployment
target: kubernetes:service_account
operational_rules:
  - configuration_rules:
      - resource: '{{ .Source }}'
        configuration:
          field: Object.spec.template.spec.serviceAccountName
          value: '{{ .Target }}'
