source: kubernetes:persistent_volume_claim
target: kubernetes:namespace
operational_rules:
  - configuration_rules:
      - resource: '{{ .Source }}'
        configuration:
          field: Object.metadata.namespace
          value: '{{ .Target }}'
