source: kubernetes:persistent_volume_claim
target: kubernetes:storage_class
operational_rules:
  - configuration_rules:
      - resource: '{{ .Source }}'
        configuration:
          field: Object.spec.storageClassName
          value: '{{ .Source.Object.metadata.name }}'
