source: kubernetes:pod
target: kubernetes:service_account
operational_rules:
  - configuration_rules:
      - resource: '{{ .Source }}'
        configuration:
          field: Object.Spec.ServiceAccountName
          value: '{{ .Target }}'
