source: kubernetes:pod
target: kubernetes:service_account
operational_rules:
  - configuration_rules:
    - resource: '{{ .Target }}'
      configuration:
        field: Object.metadata.annotations
        value:
          "helm.sh/hook": pre-install