source: kubernetes:service
target: kubernetes:pod
operational_rules:
  - configuration_rules:
      - resource: '{{ .Source }}'
        configuration:
          field: Object.Spec.Selector
          value: |
            {{ range $index, $label := (fieldValue "Object.Metadata.Labels" .Target) }}
            {{ $label.Name }}: {{ $label.Value }}
            {{ end }}
      - resource: '{{ .Source }}'
        configuration:
          field: Object.Spec.Ports
          value: |
            {{ range $index, $container := (fieldValue "Object.Spec.Containers" .Target)  }}
              {{ range $index, $port := $container.Ports }}
            - Name: '{{ .Target.Name }}-{{ $container.Name }}-{{ $port.ContainerPort}}'
              Protocol:   {{ $port.Protocol }}
              Port:       {{ $port.HostPort }}
              TargetPort: {{ $port.ContainerPort }}
              {{ end }}
            {{ end }}

  - if: |
      {{hasUpstream "kubernetes:target_group_binding" .Source }}
    configuration_rules:
      - resource: '{{ .Target }}'
        configuration:
          field: Object.Labels
          value:
            elbv2.k8s.aws/pod-readiness-gate-inject: enabled