on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
concurrency:
  cancel-in-progress: true
  group: govulncheck-${{ github.ref }}
name: govulncheck
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.5'
          cache-dependency-path: go.sum
      - name: Install
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run
        run: |
          touch pkg/auth/auth0_client_secret.key
          govulncheck ./...
