on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
concurrency:
  cancel-in-progress: true
  group: govulncheck-${{ github.ref }}
name: govulncheck
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.0'
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/checkout@v3
      - name: Install
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run
        run: |
          touch pkg/auth/auth0_client_secret.key
          govulncheck ./...
