on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
concurrency:
  cancel-in-progress: true
  group: linter-${{ github.ref }}
name: golangci-lint
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.3'
          cache-dependency-path: go.sum
      - name: Stub auth secret
        run: |
          touch pkg/auth/auth0_client_secret.key
      - name: Run Go linter
        uses: golangci/golangci-lint-action@v3
        with:
          # Since we use actions/cache, disable the native caching
          # https://github.com/golangci/golangci-lint-action/issues/244
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout=10m
