on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
concurrency:
  cancel-in-progress: true
  group: unit-tests-${{ github.ref }}
name: unit tests
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.3'
          cache-dependency-path: go.sum
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: pipenv
      - name: Test setup
        run: |
          pip install pipenv
          pipenv --python 3.12
          pipenv install --dev

          touch pkg/auth/auth0_client_secret.key
      - name: Run test
        run: |
          go test -race -v -coverprofile=c.out ./...

      - name: Update coverage report
        if: github.ref_name == 'main'
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: c.out
          chart: true
          reuse-go: true
