on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
concurrency:
  cancel-in-progress: true
  group: unit-tests-${{ github.ref }}
name: unit tests
permissions:
  contents: write
env:
  GOEXPERIMENT: 'rangefunc'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22.0'
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            ~\AppData\Local\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install lang servers
        run: |
          python3 -m pip install python-lsp-server[all]

      - name: Run test
        run: |
          touch pkg/auth/auth0_client_secret.key
          export PATH=$HOME/.local/bin:$PATH
          go test -race -v -coverprofile=c.out ./...

      - name: Update coverage report
        if: github.ref_name == 'main'
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: c.out
          chart: true
          reuse-go: true
